version: "3.7"


services:
  mongodb:
    image: mongo:5
    volumes:
      - db-data:/data/db
      - ./api/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SELF_URL: http://localhost:8000/api
      DATABASE_URL: mongodb://admin:admin@mongodb:27017/
  
  rates_service:
    build:
      context: ./rates-service
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    environment:
      API_URL: http://localhost:8000
      CRYPTOCOMPARE_API_URL: https://min-api.cryptocompare.com
      FETCH_INTERVAL_SEC: 5
      TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InFyX2NhcGl0YWxAZW1haWwuY29tIiwibmFtZSI6InFyIGNhcGl0YWwiLCJpZCI6IjYyYzZlYjVjOTgzMmU3N2ZiZWU1ODQ1YSJ9.g4m2eHsJXLxvTfQtk6dSd5M0r7L7BQFDj9K-hT8Hsfo

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      REACT_APP_API_ENDPOINT: http://localhost:8000/api
      REACT_APP_IS_DEVELOPMENT: "true"
volumes:
  db-data: